name: CI

on: [push]

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          gem update --system
          bundle update
      - name: Run specs
        run: |
          bundle exec rake spec
